"""initial schema

Revision ID: 5ec5b8899f44
Revises: 
Create Date: 2026-09-08 15:37:07.667504
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '5ec5b8899f44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('base_url', sa.String(length=1024), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('endpoint_path', sa.String(length=255), nullable=False),
    sa.Column('extra_headers', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('admin_only', sa.Boolean(), nullable=False),
    sa.Column('default_params', sa.JSON(), nullable=False),
    sa.Column('forced_params', sa.JSON(), nullable=False),
    sa.Column('allowed_param_keys', sa.JSON(), nullable=False),
    sa.Column('supports_temperature', sa.Boolean(), nullable=False),
    sa.Column('supports_system_prompt', sa.Boolean(), nullable=False),
    sa.Column('supports_json_mode', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('reasoning_mode', sa.String(length=16), nullable=False),
    sa.Column('reasoning_payload', sa.JSON(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=False),
    sa.Column('tpm_limit', sa.Integer(), nullable=False),
    sa.Column('request_timeout', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('max_tokens_cap', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_source', sa.Enum('local', 'oidc', name='authsource', native_enum=False, length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oidc_issuer', sa.String(length=512), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_issuer', 'oidc_subject', name='uq_user_oidc'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('model_config_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'paused', 'succeeded', 'completed', 'failed', 'canceled', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('resolved_params', sa.JSON(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('input_filename', sa.String(length=512), nullable=False),
    sa.Column('input_path', sa.String(length=1024), nullable=False),
    sa.Column('input_size', sa.BigInteger(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=False),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_user_created', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_table('job_errors',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_errors_job', 'job_errors', ['job_id', 'item_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_errors_job', table_name='job_errors')
    op.drop_table('job_errors')
    op.drop_index('ix_jobs_user_created', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('model_configs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
